lsst-epo/investigations-api

.github/workflows/develop-pr-gae.yaml
.github/workflows/develop-push-gae.yaml
.github/workflows/main-push-gae.yaml

EPO-8491 Updated workflow files

Updated workflow files

---

.github/workflows/develop-pr-gae.yaml
.github/workflows/develop-push-gae.yaml
.github/workflows/main-pr-gae.yaml
.github/workflows/main-push-gae.yaml

Fixed syntax error in workflow file

---

api/config/general.php

EPO-8521 Override runQueueAutomatically default value for supervisord

Override runQueueAutomatically default value

---

api/config/project/entryTypes/default--021f7cc6-93ec-4da4-9566-8d05c64d1725.yaml
api/config/project/fields/answerType--a966d509-84b0-43ab-9a5b-42590a5fb537.yaml
api/config/project/fields/questionText--919ed98f-d33e-4fae-adc0-2253a155246f.yaml
api/config/project/fields/widgetInstructions--0fd14cd3-7b23-4230-adce-9cfa16050740.yaml
api/config/project/project.yaml

Add textarea as an `answerType` and differentiate between plaintext labels and Redactor fields for widget instructions

[F] textarea question type

---

api/config/project/entryTypes/homepage--6f0c128e-9978-41c2-b982-dcdf3933b0e2.yaml
api/config/project/fields/homepageContentBlocks--40c867bb-c75a-4d5f-8d69-e7facae1c15b.yaml
api/config/project/fields/investigationEntries--048379b3-5d56-46a2-bfe2-9690b4b57151.yaml
api/config/project/neoBlockTypes/image--4e9ea915-78e8-4b28-b44e-fe2af60c77f8.yaml
api/config/project/neoBlockTypes/investigationGrid--f4b5a1d9-424f-4bc1-a2ea-37b302b8dc32.yaml
api/config/project/neoBlockTypes/text--a1eeb085-4a92-48ba-92f5-65b9f5ebfc72.yaml
api/config/project/project.yaml

JIRA: https://jira.lsstcorp.org/browse/EPO-8616>
Homepage single has its own special set on ContentBlocks which includes:
- TextBlock
- ImageBlock
- new InvestigationGrid
This PR uses the `investigations-client` PR: https://github.com/lsst-epo/investigations-client/pull/78.  
Go into the CMS and update the homepage with some content and stuff.  Check that image, text, and investigationGrid blocks all render as expected on the frontend.

[EPO-8616] Homepage ContentBlocks

---

api/config/project/entryTypes/investigationParent--bfaa63c2-dd2c-42c8-b68e-79d0180d5146.yaml
api/config/project/fields/helpUrl--c1c8acb5-0649-4dca-a7c8-1d03e98097cf.yaml
api/config/project/globalSets/menuContent--0edce3a2-c596-4238-9dde-212c83d5a65f.yaml
api/config/project/graphql/schemas/04341069-ff31-4470-970a-8c7e82ec37eb.yaml
api/config/project/graphql/schemas/cec04a25-43ba-4f4c-81bd-b71f48731b5a.yaml
api/config/project/graphql/schemas/e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee.yaml
api/config/project/project.yaml

API for menu content, adds an acknowledgements field to the parent page of investigations and a global help url

[C] menu content

---

api/config/project/categoryGroups/sortOptions--90aa9610-a9c9-4531-95f8-d0068046ae25.yaml
api/config/project/graphql/schemas/04341069-ff31-4470-970a-8c7e82ec37eb.yaml
api/config/project/graphql/schemas/cec04a25-43ba-4f4c-81bd-b71f48731b5a.yaml
api/config/project/graphql/schemas/e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee.yaml
api/config/project/project.yaml
api/config/project/sections/homepage--075467b0-0dee-453c-9df0-0de6d2443cf8.yaml
api/config/project/sections/investigations--1a93d10f-deca-4e6b-a3e8-9baae53e7c47.yaml
api/config/project/sections/pages--8dc1c6cb-eb37-4ad7-b9c8-7d0891fcd42d.yaml
api/config/project/sections/questions--9068dd8e-ad92-4925-ba1d-1fe180598462.yaml
api/config/project/sections/referenceModals--c2356ed1-1e49-4056-83c7-ed615a2694b1.yaml
api/config/project/sections/widgets--28704998-935a-423b-a405-d4ad8b38efa2.yaml
api/config/project/sites/fr--356c97b0-54e5-44bb-901e-9d92a314134f.yaml

Add French site, added to schemas, and added to all sections. See client for testing.

[C] add French support

---

api/config/project/entryTypes/cameraFilterTool--0e4edcac-f39e-4825-946b-7174494adb63.yaml
api/config/project/entryTypes/colorFilterTool--d2e48b83-d161-48b9-b0a9-5c21914b5931.yaml
api/config/project/entryTypes/default--021f7cc6-93ec-4da4-9566-8d05c64d1725.yaml
api/config/project/entryTypes/default--4f04d6b0-64ef-454b-b343-66181c08dda9.yaml
api/config/project/project.yaml
api/config/project/sections/widgets--28704998-935a-423b-a405-d4ad8b38efa2.yaml

For JIRA: "EPO-8859 #IN-REVIEW #comment add display name to entry fields"

[C] add display name to entry fields

---

api/composer.json
api/composer.lock
api/config/general.php
api/config/project/project.yaml
api/config/project/sections/investigations--1a93d10f-deca-4e6b-a3e8-9baae53e7c47.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml
docker-compose-local-db.sample.yml

JIRA: https://jira.lsstcorp.org/browse/EPO-8857
Set preview targets from env var + aliasing in `general.php`
⭐ N.B. Renamed NEXT_REVALIDATE_SECRET_TOKEN to NEXT_SECRET_TOKEN. Will need to update on your local before testing, and in GCP secrets before deployment ⭐
I hate to do it but also includes some not related changes that were just on my mind:
- Editors group had permissions for create/edit/destroy all content entry types
- Editors group had permissions for using the DAM plugin fields
- DAM plugin upgrade to 4.0.11
https://github.com/lsst-epo/investigations-client/pull/105 depends on this PR.
1. Go to homepage or investigations entry
2. Make a change
3. Save entry
4. Visit page on the frontend
5. Confirm changes are live on the frontend
1. Go to homepage or investigations entry
2. …

[EPO-8857] Revalidation & Preview support for next

---

api/config/general.php
api/config/project/project.yaml

JIRA: https://jira.lsstcorp.org/browse/EPO-8949
By its very nature I feel like signing up using OAuth is a sufficient level of verification, and that explicitly verifying one's email is a step more pertinent when signing up with an arbitrary email and password in text fields.
I swear I only checked the one box in the GraphQL Auth plugin settings for skipping the email verification step but it precipitated like a whole much of minor changes all over the `project.yaml`.  Nothing that looks too weird so I am willing to hope/assume it's just like shuffling whitespace around or whatever.
To whom it may concern, the `GOOGLE_APP_SECRET` env var in docker-compose is actually never used.  Not sure why we thought it was needed, maybe it was used by a pervious version of the plugin that predated …

[EPO-8949] Google authed users immediately activated

---

api/composer.json
api/composer.lock
api/config/project/fields/video--118a3e01-4188-4f83-be5b-f4ce24d7513e.yaml
api/config/project/neoBlockTypeGroups/513634e9-3389-4e41-b769-9433ac34e35e.yaml
api/config/project/neoBlockTypeGroups/7ebe493b-5e03-48c8-8375-c9f9582da77e.yaml
api/config/project/neoBlockTypes/barGraphTool--a47f94c7-0a32-43be-863a-fa9d6636fff2.yaml
api/config/project/neoBlockTypes/cameraFilterTool--87fc48a5-a399-4ce1-a7ca-2dadfd1e1445.yaml
api/config/project/neoBlockTypes/colLeft--947400f5-3c2d-403a-b94e-68715e48a9c0.yaml
api/config/project/neoBlockTypes/colRight--efbf1b30-4cb7-4361-9f45-016d119aec06.yaml
api/config/project/neoBlockTypes/colorFilterToolBlock--0d06751e-ecf9-4281-a754-8c818fb9353b.yaml
api/config/project/neoBlockTypes/filterTool--3912a1a0-e71b-44b3-bcf4-976c0564975e.yaml
api/config/project/neoBlockTypes/group--ba6494d9-36e8-40ee-9284-c56783357043.yaml
api/config/project/neoBlockTypes/scatterplotTool--5b8a79d6-e9d6-44d2-b986-36bf0bf74131.yaml
api/config/project/neoBlockTypes/twoColumnContainer--1ed0caa3-b91f-442b-b313-f3eb54a8a0dc.yaml
api/config/project/neoBlockTypes/video--d27f27b6-dfb4-4c6a-9196-ab3c81785d87.yaml
api/config/project/project.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml

API branch for the video content block feature, should be tested using the client. Includes latest DAM plugin and update to settings for it's functionality.

[F] Video content block

---

api/config/project/project.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml
api/config/project/users/groups/translators--56e28243-1126-458f-b20a-41078120d186.yaml

For JIRA: "EPO-8983 #IN-REVIEW #comment update user permissions"
For editors:
- Streamline permissions, editors can view/create/save/delete theirs or anyone else's work
- Access to all locales
For translators: 
- Can view and save any existing entries
- No editing access on any sites by default, will need to select the locale site specific to their translation work.

[C] update editor permissions and add translator role

---

api/config/project/neoBlockTypes/cameraFilterTool--87fc48a5-a399-4ce1-a7ca-2dadfd1e1445.yaml
api/config/project/neoBlockTypes/colorFilterToolBlock--0d06751e-ecf9-4281-a754-8c818fb9353b.yaml
api/config/project/neoBlockTypes/filterTool--3912a1a0-e71b-44b3-bcf4-976c0564975e.yaml
api/config/project/neoBlockTypes/text--5548ce5c-5ad4-494e-93be-8ff129618d20.yaml
api/config/project/project.yaml

Adds widget instructions to the two existing static widgets (camera filter and filter tool)

[C] add instructions to static widgets

---

api/config/project/entryTypes/sourceSelector--297d2268-f298-40a1-bec3-a1c836a69e38.yaml
api/config/project/entryTypes/supernovaGalaxyObservations--5e789abf-cfef-4ed4-b795-a4dcfe4fd284.yaml
api/config/project/fieldGroups/e1b23b33-c33f-4c74-9811-250c2cc2789a.yaml
api/config/project/fields/alertSources--d18f36fd-9d74-4ba6-b860-25958b1d9182.yaml
api/config/project/fields/dataset--a4afde15-f983-4c30-b0d7-e0b56871e4de.yaml
api/config/project/fields/dec--f5a2bb9c-1491-4439-a169-d9b2891433a1.yaml
api/config/project/fields/distance--6dbf8441-fd70-4b44-a2f8-7b9ba10b20d9.yaml
api/config/project/fields/filter--3c999a34-b334-4792-bd8f-2c8cfb4100af.yaml
api/config/project/fields/galacticLatitude--693f669b-ba6e-4c91-adad-2543fcd62554.yaml
api/config/project/fields/galacticLongitude--ad74ba83-53f4-4102-94e9-e9eea0d31171.yaml
api/config/project/fields/imageAlbum--c489f84c-509c-4078-9b71-1e3493e17620.yaml
api/config/project/fields/json--a03e80f0-77ce-4b03-abf5-76a0deb264a9.yaml
api/config/project/fields/mjd--b78d733b-bfca-4d0c-9474-d40c87566945.yaml
api/config/project/fields/ra--0e914cfb-a2de-4721-b23b-3b1268529baf.yaml
api/config/project/fields/sourceSelector--e17c94af-1953-42af-939c-e3ed84c62a95.yaml
api/config/project/graphql/schemas/04341069-ff31-4470-970a-8c7e82ec37eb.yaml
api/config/project/graphql/schemas/cec04a25-43ba-4f4c-81bd-b71f48731b5a.yaml
api/config/project/graphql/schemas/e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee.yaml
api/config/project/matrixBlockTypes/source--af7d475a-5acc-4523-9acf-257ac909e7ec.yaml
api/config/project/neo/orders/2599f40c-bfbc-4db6-bf56-cb9f48ad01bf.yaml
api/config/project/neoBlockTypes/filterimage--f7ef882a-9d5d-4247-9e24-27d4a2702508.yaml
api/config/project/neoBlockTypes/sourceSelectorBlock--430f132d-8145-4e49-ba49-e9b839f7898e.yaml
api/config/project/project.yaml
api/config/project/sections/datasets--fbfbf05d-c7e1-4f6c-a093-47065f8d5095.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml

Adds the Supernova Datasets and Source Selector Widget back to API

[F] Supernova dataset redo

---

api/config/project/fields/binSize--a81f2835-5fbe-4fa9-a636-eafeaee155c3.yaml
api/config/project/neo/orders/a46e7379-7773-4ce4-9c59-434567870f0c.yaml
api/config/project/neoBlockTypes/colLeft--947400f5-3c2d-403a-b94e-68715e48a9c0.yaml
api/config/project/neoBlockTypes/colRight--efbf1b30-4cb7-4361-9f45-016d119aec06.yaml
api/config/project/neoBlockTypes/group--ba6494d9-36e8-40ee-9284-c56783357043.yaml
api/config/project/neoBlockTypes/supernovaDistanceDistribution--7033117c-c3b9-4794-9a6d-cbbbae2010af.yaml
api/config/project/project.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml

API for Supernova Distance & Distribution widget
In Craft, should be able to:
- Add a Supernova Distance & Distribution widget in a Content Block
- Upload a JSON file with the data for the widget
- Define a bin size
- Add an image album for the widget
- Add an existing supernova dataset to the widget

[F] Supernova Distance & Distribution

---

api/composer.json
api/composer.lock

Upgraded DAM plugin version to `v4.1.0`

Upgraded DAM plugin version to `v4.1.0`

---

api/config/project/entryTypes/default--021f7cc6-93ec-4da4-9566-8d05c64d1725.yaml
api/config/project/fields/answerType--a966d509-84b0-43ab-9a5b-42590a5fb537.yaml
api/config/project/fields/displayTable--56bdf2e8-b9b4-425d-a189-fc7b22f5d169.yaml
api/config/project/fields/questionTable--fcc60644-81ac-4f94-ad34-8bdaeeb4a6b6.yaml
api/config/project/matrixBlockTypes/question--6e046cd9-797f-4e30-9959-143cfa694b2f.yaml
api/config/project/matrixBlockTypes/static--109801b3-a2ef-425d-ab7f-f816ea7dd13b.yaml
api/config/project/matrixBlockTypes/tableCell--7c04d87d-2b5d-4ba8-841a-2d4f2a1047dd.yaml
api/config/project/project.yaml
api/config/project/superTableBlockTypes/19f441a5-4dd4-4084-997f-57a9830c3ee7.yaml
api/config/project/superTableBlockTypes/29607c37-0de8-47e7-a4ca-a12d73abe611.yaml
api/config/project/superTableBlockTypes/8d38f778-7063-4c61-a56d-484560c150f1.yaml

Adds tabular questions and the ability to display them in content blocks, see client for full details

[F] Tabular questions

---

Makefile

Changed query param to POST for export

Changed query param to POST for export

---

api/config/project/entryTypes/default--021f7cc6-93ec-4da4-9566-8d05c64d1725.yaml
api/config/project/entryTypes/sourceSelector--297d2268-f298-40a1-bec3-a1c836a69e38.yaml
api/config/project/fields/answerType--a966d509-84b0-43ab-9a5b-42590a5fb537.yaml
api/config/project/fields/equation--e28ed79c-82dd-4c7b-b1cf-abdece40ff5e.yaml
api/config/project/fields/lightCurveTool--466246f6-753b-4198-8067-18acf1a7d4cb.yaml
api/config/project/graphql/schemas/04341069-ff31-4470-970a-8c7e82ec37eb.yaml
api/config/project/graphql/schemas/cec04a25-43ba-4f4c-81bd-b71f48731b5a.yaml
api/config/project/graphql/schemas/e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee.yaml
api/config/project/neo/orders/2599f40c-bfbc-4db6-bf56-cb9f48ad01bf.yaml
api/config/project/neo/orders/a46e7379-7773-4ce4-9c59-434567870f0c.yaml
api/config/project/neoBlockTypes/lightCurveBlock--528d82d4-91db-4ee9-9fa2-8d8c7c871c5e.yaml
api/config/project/neoBlockTypes/magnitudeScatterPlot--a02a930a-9f54-4ae2-8bb2-0e0ab7713759.yaml
api/config/project/project.yaml

Adds calculator question type, see client for details

[C] add calculator type questions

---

api/config/project/entryTypes/default--021f7cc6-93ec-4da4-9566-8d05c64d1725.yaml
api/config/project/fields/answerType--a966d509-84b0-43ab-9a5b-42590a5fb537.yaml
api/config/project/fields/maximum--d5901e55-99c9-441a-937e-05a065d6e60b.yaml
api/config/project/fields/minimum--79f2f742-966c-42df-9d04-8492d456325c.yaml
api/config/project/fields/precision--24f2e959-23a9-4f1a-8394-0849fb85b85b.yaml
api/config/project/fields/validation--37af5dda-9a0b-458a-b48c-1bd31b9170af.yaml
api/config/project/matrixBlockTypes/numberValidator--c4a0ba18-ffd2-4399-b068-0fac98fee410.yaml
api/config/project/project.yaml

[F] add number question and validations

---

Makefile
README.md
db/Dockerfile

Updated `Makefile` and updated README.md instructions

Updated `Makefile` and updated README.md instrctns

---

api/config/project/entryTypes/default--021f7cc6-93ec-4da4-9566-8d05c64d1725.yaml
api/config/project/fields/displayTable--56bdf2e8-b9b4-425d-a189-fc7b22f5d169.yaml
api/config/project/fields/questionTable--fcc60644-81ac-4f94-ad34-8bdaeeb4a6b6.yaml
api/config/project/fields/tableHeader--f633c7c8-51d2-4e26-93a0-630d539e83f7.yaml
api/config/project/matrixBlockTypes/previousQuestion--997d2cc5-340b-48d0-9f44-032b2c6ec179.yaml
api/config/project/matrixBlockTypes/previousQuestion--d6180a2a-48c9-42ce-a80f-8721282a126d.yaml
api/config/project/matrixBlockTypes/question--6e046cd9-797f-4e30-9959-143cfa694b2f.yaml
api/config/project/matrixBlockTypes/rowHeader--418ea0f0-379d-4ee5-8dab-f82b6a62c191.yaml
api/config/project/matrixBlockTypes/rowHeader--5a7221ec-779f-4433-b5b7-732d6b0babd5.yaml
api/config/project/matrixBlockTypes/static--109801b3-a2ef-425d-ab7f-f816ea7dd13b.yaml
api/config/project/matrixBlockTypes/tableCell--58dc56f1-d17a-424b-9aac-650a83f6b919.yaml
api/config/project/neoBlockTypes/table--7b30c218-6328-41a2-a3e3-2575559f4c9c.yaml
api/config/project/project.yaml
api/config/project/superTableBlockTypes/19f441a5-4dd4-4084-997f-57a9830c3ee7.yaml
api/config/project/superTableBlockTypes/29607c37-0de8-47e7-a4ca-a12d73abe611.yaml
api/config/project/superTableBlockTypes/48d0c9f8-9c08-45c2-bd17-1b7a18d4e4a5.yaml
api/config/project/superTableBlockTypes/8d38f778-7063-4c61-a56d-484560c150f1.yaml

[C] allow number, text, textarea in table cells

---

api/config/project/fields/questionTable--fcc60644-81ac-4f94-ad34-8bdaeeb4a6b6.yaml
api/config/project/matrixBlockTypes/question--6e046cd9-797f-4e30-9959-143cfa694b2f.yaml
api/config/project/project.yaml
api/config/project/superTableBlockTypes/29607c37-0de8-47e7-a4ca-a12d73abe611.yaml
api/config/project/superTableBlockTypes/8d38f778-7063-4c61-a56d-484560c150f1.yaml

[C] uncap table rows

---

README.md

Updated `README.md` w/DB script context

Updated `README.md` w/DB script context

---

api/config/project/neo/orders/29f139cc-2d9b-4e10-afce-1e6a70105e2b.yaml
api/config/project/neoBlockTypes/multiselect--28bf8eda-b10b-4aaa-98fd-d52d6c95ef57.yaml
api/config/project/neoBlockTypes/number--756208ab-5aac-4a28-bce2-5b3d9b5e7563.yaml
api/config/project/neoBlockTypes/readonlyText--e7b953ca-6424-4d14-bc2c-393d3f8410a4.yaml
api/config/project/neoBlockTypes/select--8365851b-c952-499c-84dc-c9e054b83e84.yaml
api/config/project/neoBlockTypes/text--220292c8-0330-4dd4-aa84-f0eeec38fa4e.yaml
api/config/project/project.yaml

Added numbers with validations as a block type for multi-part questions

[C] multipart number questions

---

Makefile
api/config/project/matrixBlockTypes/source--af7d475a-5acc-4523-9acf-257ac909e7ec.yaml
api/config/project/project.yaml

Update the x, y, and radius values of sources to reflect percents

[C] change alert sources to percents

---

api/config/project/entryTypes/sourceSelector--297d2268-f298-40a1-bec3-a1c836a69e38.yaml
api/config/project/fields/lightCurveTool--466246f6-753b-4198-8067-18acf1a7d4cb.yaml
api/config/project/graphql/schemas/04341069-ff31-4470-970a-8c7e82ec37eb.yaml
api/config/project/graphql/schemas/cec04a25-43ba-4f4c-81bd-b71f48731b5a.yaml
api/config/project/graphql/schemas/e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee.yaml
api/config/project/neoBlockTypes/lightCurveBlock--528d82d4-91db-4ee9-9fa2-8d8c7c871c5e.yaml
api/config/project/neoBlockTypes/magnitudeScatterPlot--a02a930a-9f54-4ae2-8bb2-0e0ab7713759.yaml
api/config/project/project.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml
api/config/project/users/groups/translator--ce6530be-a702-47b4-b96e-f34aa9f55eb2.yaml

Add a new group for translators and add additional permissions to editors

[C] create Translator user group

---

api/composer.json
api/composer.lock

fix: update `lsst-epo/canto-dam-assets`

---

.github/workflows/develop-push-gae.yaml
.github/workflows/main-push-gae.yaml
.github/workflows/main-release-tag.yaml

Explicitly name Docker images

---

.github/workflows/develop-push-gae.yaml

Added .env step before build step of dev workflow

Added .env step before build step of dev workflow

---

.github/workflows/main-push-gae.yaml
.github/workflows/main-release-tag.yaml

Aligned `int` and `prod` workflows with `dev`

Aligned `int` and `prod` worklows with `dev`

---

api/config/project/entryTypes/default--4f04d6b0-64ef-454b-b343-66181c08dda9.yaml
api/config/project/fields/referenceModalEntries--55ef91b0-a2ba-4935-8d49-9e3e1d3dcc91.yaml
api/config/project/graphql/schemas/04341069-ff31-4470-970a-8c7e82ec37eb.yaml
api/config/project/graphql/schemas/cec04a25-43ba-4f4c-81bd-b71f48731b5a.yaml
api/config/project/graphql/schemas/e2951ac7-e91a-4d8a-964f-50c6b6e0b1ee.yaml
api/config/project/neo/orders/a46e7379-7773-4ce4-9c59-434567870f0c.yaml
api/config/project/neoBlockTypes/referenceModalBlock--53df9537-d85e-4fd3-9e4c-b203594ada7c.yaml
api/config/project/project.yaml
api/config/project/sections/referenceModals--c2356ed1-1e49-4056-83c7-ed615a2694b1.yaml
api/config/project/users/groups/editors--8f49c843-6aaa-49bf-ac19-21a9800c4760.yaml
api/config/project/users/groups/translator--ce6530be-a702-47b4-b96e-f34aa9f55eb2.yaml

Reverts lsst-epo/investigations-api#142

Revert "refactor: rename Reference Modals to Reference Content"

---

.github/workflows/main-release-tag.yaml

Regression fix: added back tag to `prod` instance name

Regression fix: added back tag to `prod` release

---

api/config/app.php

Queue TTR configurable via env var

Queue TTR configurable via env var

---

api/composer.lock

Bumped DAM plugin version

---

.github/workflows/build-and-push.yaml

Adds the build and deploy workflow for Kubernetes

Add k8s workflow

---

.github/workflows/build-and-push.yaml

Update image names to create K8s image

Change image names to reflect k8s images

---

.github/workflows/build-and-push.yaml

Update images for k8s

---

api/composer.json
api/composer.lock

Bumped `craft-next-js-builds` plugin version

Bumped `craft-next-js-builds` plugin version

---

.gitignore
README.md
db/README.md

chore: update `README.md` and add `db/README.md`

chore: update `README.md` and add `db/README.md`
